version: '3.8'

services:
  petName:
    build: .
    image: petname
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
    volumes:
      - .:/app # Mount the current directory (host) to the /app directory (container)
      - ./repofolder:/code_to_refactor # Mount the repofolder directory (host) to the /code_to_refactor directory (container)
      - ./refactored:/refactored